### PR TITLE
WIP

### LINKED ISSUE #51: RuptureSet analysis report should list sections beneath each ruptoon
**As SRM Team**

**We want** to see the fault names and section ids for each rupture image

**So that** it's easy to identify these rupture examples

In the example below there'll be a list of 14 fault names + ids

image

### PR DESCRIPTION
**Pull request by voj**
Satisfies and closes https://github.com/GNS-Science/nshm-nz-opensha/issues/51

### CODE REVIEW

**Comment by voj** [comment]
The commit message needs to be fixed before merging

**Review by chrisbc — APPROVED** [review]
:+1: nice

**Comment by chrisbc** [comment]
@voj I think @ornearius is setting up travis, but the tests (upstream) still fail.

**Comment by voj** [comment]
@chrisbc I think we can see the upstream tests are failing *because* @ornearius set it up

**Pull request merged**
